# Generated by Django 4.2.23 on 2025-06-22 03:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', models.FloatField(help_text='새로운 경험과 창의성에 대한 개방 정도', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='개방성')),
                ('conscientiousness', models.FloatField(help_text='책임감과 계획성 정도', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='성실성')),
                ('extraversion', models.FloatField(help_text='사교성과 활동성 정도', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='외향성')),
                ('agreeableness', models.FloatField(help_text='협조성과 신뢰성 정도', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='친화성')),
                ('neuroticism', models.FloatField(help_text='감정적 안정성 정도', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='신경성')),
                ('movies_analyzed', models.IntegerField(verbose_name='분석된 영화 수')),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='신뢰도 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='분석 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '성격 분석',
                'verbose_name_plural': '성격 분석들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValueAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creativity_innovation', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='창의성과 혁신')),
                ('social_connection', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='사회적 연결')),
                ('achievement_success', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='성취와 성공')),
                ('harmony_stability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='조화와 안정')),
                ('authenticity_depth', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='진정성과 깊이')),
                ('personality_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='analysis.personalityanalysis', verbose_name='성격 분석')),
            ],
            options={
                'verbose_name': '가치관 분석',
                'verbose_name_plural': '가치관 분석들',
            },
        ),
    ]
