# Generated by Django 4.2.23 on 2025-06-21 13:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True, verbose_name='TMDB ID')),
                ('title', models.CharField(max_length=255, verbose_name='영화 제목')),
                ('original_title', models.CharField(max_length=255, verbose_name='원제')),
                ('overview', models.TextField(blank=True, verbose_name='줄거리')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='개봉일')),
                ('genres', models.JSONField(default=list, verbose_name='장르 목록')),
                ('melodrama_score', models.FloatField(default=0.0, verbose_name='멜로드라마 점수')),
                ('comic_score', models.FloatField(default=0.0, verbose_name='코미디 점수')),
                ('violent_score', models.FloatField(default=0.0, verbose_name='액션/폭력 점수')),
                ('imaginative_score', models.FloatField(default=0.0, verbose_name='상상력 점수')),
                ('exciting_score', models.FloatField(default=0.0, verbose_name='스릴러 점수')),
                ('poster_path', models.CharField(blank=True, max_length=255, verbose_name='포스터 경로')),
                ('vote_average', models.FloatField(default=0.0, verbose_name='평점')),
                ('popularity', models.FloatField(default=0.0, verbose_name='인기도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '영화',
                'verbose_name_plural': '영화들',
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='UserMoviePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점 (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='평가일')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='영화')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 영화 선호도',
                'verbose_name_plural': '사용자 영화 선호도들',
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
