# Generated by Django 4.2.23 on 2025-06-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True, verbose_name='TMDB 장르 ID')),
                ('name', models.CharField(max_length=50, verbose_name='장르명')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='장르명(영어)')),
            ],
            options={
                'verbose_name': '장르',
                'verbose_name_plural': '장르들',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-popularity', '-vote_average'], 'verbose_name': '영화', 'verbose_name_plural': '영화들'},
        ),
        migrations.AlterModelOptions(
            name='usermoviepreference',
            options={'ordering': ['-created_at'], 'verbose_name': '사용자 영화 선호도', 'verbose_name_plural': '사용자 영화 선호도들'},
        ),
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=False, verbose_name='성인 영화'),
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='배경 이미지 경로'),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='상영시간(분)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.BooleanField(default=False, verbose_name='비디오'),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='투표 수'),
        ),
        migrations.AddField(
            model_name='usermoviepreference',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기'),
        ),
        migrations.AddField(
            model_name='usermoviepreference',
            name='review',
            field=models.TextField(blank=True, verbose_name='리뷰'),
        ),
        migrations.AddField(
            model_name='usermoviepreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='usermoviepreference',
            name='watch_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='관람일'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='원제'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0.0, verbose_name='TMDB 평점'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.genre', verbose_name='장르들'),
        ),
    ]
